language: cpp
sudo: required
compiler:
   - gcc
branches:
  only:
  - master
#  - stable
before_install:
   - sudo apt-get update
notifications:
  recipients:
    - jakezhang1989@gmail.com
  email:
    on_success: change
    on_failure: always
script: cd gecoengine/src && make